# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GptQuiz < Formula
  desc ""
  homepage "https://github.com/rsaryev/gpt-quiz"
  version "0.0.1"

  on_macos do
    url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.1/gpt-quiz_0.0.1_darwin_all.tar.gz"
    sha256 "10cae17b5de7bc344913da7e5f59a3227caafc4c2deddb6ff6c5eef17b23a952"

    def install
      bin.install "gpt-quiz"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.1/gpt-quiz_0.0.1_linux_amd64.tar.gz"
      sha256 "1be6d65e24e540e15fc792ab88a6d15f00ecefb047f379f1feb9f8d1737f6328"

      def install
        bin.install "rsaryev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.1/gpt-quiz_0.0.1_linux_arm64.tar.gz"
      sha256 "8c533a9a8aab38dadeded2d0b4a141d00f49c766cac942dace719878253dedcf"

      def install
        bin.install "rsaryev"
      end
    end
  end
end
