# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GptQuiz < Formula
  desc ""
  homepage "https://github.com/rsaryev/gpt-quiz"
  version "0.0.2"

  on_macos do
    url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.2/gpt-quiz_0.0.2_darwin_all.tar.gz"
    sha256 "2d8fe1ed8bcdba6fcf5c10110a37aa003da250305a5a6e61f76210e0666bd027"

    def install
      bin.install "gpt-quiz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.2/gpt-quiz_0.0.2_linux_arm64.tar.gz"
      sha256 "8077b2ccf353f08aed563f6aa404a0e05492ce777e6d20460c0b26141ba13823"

      def install
        bin.install "rsaryev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.2/gpt-quiz_0.0.2_linux_amd64.tar.gz"
      sha256 "592105fb7281b518a2324766c8aa03ceb7525e78c46eee28ccc7d6cf433cbff2"

      def install
        bin.install "rsaryev"
      end
    end
  end
end
