# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GptQuiz < Formula
  desc ""
  homepage "https://github.com/rsaryev/gpt-quiz"
  version "0.0.3"

  on_macos do
    url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.3/gpt-quiz_0.0.3_darwin_all.tar.gz"
    sha256 "0b1f65b5e015d984ba5df457de06dcdf6cd7e764d079b72cc7e78dc90f4e2cbb"

    def install
      bin.install "gpt-quiz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.3/gpt-quiz_0.0.3_linux_arm64.tar.gz"
      sha256 "649a5662567bb5ea7e19a227d0b671073dfef4f8bc03d79372e1a6eb51953329"

      def install
        bin.install "rsaryev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsaryev/gpt-quiz/releases/download/0.0.3/gpt-quiz_0.0.3_linux_amd64.tar.gz"
      sha256 "60e83862a7fc6a4d69285d9a94f33f8601ac6d604be916fdcea4775689fc2baf"

      def install
        bin.install "rsaryev"
      end
    end
  end
end
